#!/bin/sh
# Build and run the charger module's host-side test against a checkout of
# nyx-lib's public headers (NYX_LIB_INCLUDE, default ../nyx-lib/include/public).
set -e
here=$(cd "$(dirname "$0")" && pwd)
top=$(cd "$here/../../.." && pwd)
nyxinc=${NYX_LIB_INCLUDE:-$top/../nyx-lib/include/public}
build=${BUILD_DIR:-/tmp}
out=$build/test_charger_resync
# nyx_version.h is generated by nyx-lib's CMake; make one from the template.
mkdir -p "$build/nyxgen/nyx/common"
sed -e 's/@NYX_API_VERSION_MAJOR@/7/' -e 's/@NYX_API_VERSION_MINOR@/0/' \
    "$nyxinc/nyx/common/nyx_version.h.in" > "$build/nyxgen/nyx/common/nyx_version.h"
${CC:-cc} -std=gnu99 -Wall -Wno-unused-function -DTEST_HOST \
    -I"$here/stubs" -I"$build/nyxgen" -I"$nyxinc" -I"$top/include/internal" -I"$top/src/utils" \
    $(pkg-config --cflags glib-2.0 libudev) \
    "$here/test_charger_resync.c" "$top/src/utils/utils.c" \
    $(pkg-config --libs glib-2.0 libudev) -o "$out"
"$out" "$@"
