#!/bin/sh
# Build and run the system module's host-side tests against a checkout of
# nyx-lib's public headers (NYX_LIB_INCLUDE, default ../nyx-lib/include/public).
#
# Covers the wakeup alarm layer and the RTC alarm watch. Neither needs a device
# or root: the alarm tests use a timerfd in this process (falling back to
# CLOCK_REALTIME without CAP_WAKE_ALARM, which they detect), and the watch tests
# stand a pipe in for /dev/rtc.
set -e
here=$(cd "$(dirname "$0")" && pwd)
top=$(cd "$here/../../.." && pwd)
nyxinc=${NYX_LIB_INCLUDE:-$top/../nyx-lib/include/public}
build=${BUILD_DIR:-/tmp}
# nyx_version.h is generated by nyx-lib's CMake; make one from the template.
mkdir -p "$build/nyxgen/nyx/common"
sed -e 's/@NYX_API_VERSION_MAJOR@/7/' -e 's/@NYX_API_VERSION_MINOR@/0/' \
    "$nyxinc/nyx/common/nyx_version.h.in" > "$build/nyxgen/nyx/common/nyx_version.h"

status=0
for t in test_system_alarm test_system_rtc_watch; do
    out=$build/$t
    ${CC:-cc} -std=gnu99 -Wall -Wno-unused-function -DTEST_HOST \
        -I"$here/stubs" -I"$build/nyxgen" -I"$nyxinc" -I"$top/include/internal" \
        $(pkg-config --cflags glib-2.0) \
        "$here/$t.c" $(pkg-config --libs glib-2.0) -o "$out"
    echo "== $t"
    "$out" "$@" || status=$?
done
exit $status
